version = 1

[[annotations]]
path = ["src/*"]
precedence = "closest"
SPDX-FileCopyrightText = "© 2009 Stephen C. Losen"
SPDX-License-Identifier = "GPL-1.0-or-later"

[[annotations]]
path = ["README.md", "lighttpd-conf/*"]
precedence = "closest"
SPDX-FileCopyrightText = "© 2019 Clifford Weinmann <https://www.cliffordweinmann.com/>"
SPDX-License-Identifier = "Unlicense"
