#!/bin/sh
# CGI script to calculate SHA1 hash for a password.
# Access at http://127.0.0.1:8080/hash/password123123123123123

echo "Content-type: text/plain; charset=utf-8"

basename=$(basename $0)
args=$(echo "$REQUEST_URI" | sed -e "s|^/$basename||" -e 's|^/||')

if [ -z "$args" ]
then
	echo -e "Status: 400 Bad Request\n"
	echo "No password specified"
	exit 0
fi

echo -e "Status: 200 OK\n"
echo -n "$args" | openssl sha1 | awk 'BEGIN { getline; print toupper($2) }'
exit 0
