#!/bin/sh

# SPDX-FileCopyrightText: © 2019 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: Unlicense

# Redirect for backward compatibility
uri=$(echo "$REQUEST_URI" | sed -e 's|^/hash|/sha1hash|')
echo 'Status: 302 Found'
echo "Location: $uri"
echo 'Content-Length: 0'
echo ''
