#!/bin/sh
# CGI script to search for a password.
# Access at http://127.0.0.1:8080/pwnedpassword/sha1hash

echo "Content-type: text/plain; charset=utf-8"

if [ ! -d /data ]; then
	echo -e "Status: 400 Bad Request\n"
	echo "Please run this container with a volume mounted at /data."
	echo 'docker run --rm -v \$(pwd):/data pwned-httpd'
	exit 0
fi

cd /data
if [ $? -ne 0 ]
then
	echo -e "Status: 400 Bad Request\n"
	echo "Could not access /data"
	exit 0
fi

basename=$(basename $0)
args=$(echo "$REQUEST_URI" | sed -e "s|^/$basename||" -e 's|^/||')

if [ -z "$args" ]
then
	echo -e "Status: 400 Bad Request\n"
	echo "No password specified"
	exit 0
fi

#echo ""
#echo "QUERY_STRING = [$QUERY_STRING]"
#echo "REQUEST_URI = [$REQUEST_URI]"
#echo "args = [$args]"

FILES="pwned-passwords-v3-ordered-by-hash"

# To search for a password, hash it first
#hash=`echo -n "$args" | openssl sha1 | awk 'BEGIN { getline; print toupper($2) }'`
# This version searches for a hash
hash=`echo -n "$args" | tr '[:lower:]' '[:upper:]'`
totalcount=0
for file in *.txt
do
	if [ -f "$file" ]
	then
		for s in $(/usr/local/bin/sgrep "$hash" "$file" | tr -d '\r')
		do
			count=$(echo "$s" | cut -f2 -d:)
			if [[ $count -ne 0 ]]; then
				echo -e "Status: 200 OK\n"
				echo "$count"
				exit 0
			fi
			totalcount=$(( $totalcount + $count ))
		done
	fi
done
if [[ $totalcount -eq 0 ]]; then
	echo -e "Status: 404 Not found\n"
	#echo "Good news - no pwnage of [$args] found!"
fi

exit 0
