#!/bin/sh

# SPDX-FileCopyrightText: © 2019 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: Unlicense

# Redirect for backward compatibility
echo 'Status: 302 Found'
echo 'Location: /healthz'
echo 'Content-Length: 0'
echo ''
