#!/bin/sh
# CGI script for Docker HEALTHCHECK
# Access at http://127.0.0.1:8080/status

echo "Content-type: text/plain; charset=utf-8"

if [ ! -d /data ]; then
	echo -e "Status: 400 Bad Request\n"
	echo "No /data directory mounted."
	exit 0
fi

if [ -f /data/*.txt ]; then
	echo -e "Status: 400 Bad Request\n"
	echo "No password file(s) found."
	exit 0
fi

echo -e "Status: 200 OK\n"
echo "pong"
exit 0
